version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    command: php artisan queue:work
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"